CREATE DATABASE ecosys;

\c ecosys;

CREATE TABLE app_user (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	country varchar(255) NULL,
	firstname varchar(255) NULL,
	lastname varchar(255) NULL,
	"password" varchar(255) NULL,
	"role" varchar(255) NULL,
	username varchar(255) NOT NULL,
	CONSTRAINT app_user_pkey PRIMARY KEY (id),
	CONSTRAINT app_user_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'USER'::character varying])::text[]))),
	CONSTRAINT uk3k4cplvh82srueuttfkwnylq0 UNIQUE (username)
);

CREATE TABLE manifiestos (
    id SERIAL PRIMARY KEY,
    folio INT NOT NULL,
    folio_dia INT, 
    fecha_manifiesto DATE,
    cliente VARCHAR(50),
    tipo_disposicion VARCHAR(50),
    num_economico INT, 
    placa VARCHAR(20),
    operador VARCHAR(75),
    ruta VARCHAR(100),
    tipo_servicio VARCHAR (50),
    archivo BYTEA,
    usuario_id INT,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);